### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by thermof** [flathub/com.mojang.Minecraft#101]
can you help me fix this on chromebooks we have to keep on loging in and its anoying and when i get stuff on creative it gltiches out waht do i do

**Comment by AsciiWolf** [comment]
Hi, thanks for reporting this issue. It was already reported as #97. Please, write you comment there. Anyway, I am unfortunately to help you with this issue since I don't have a Chromebook and this seems to be most likely a Mesa-related issue that happens only on Chromebooks.

**Comment by AsciiWolf** [comment]
Regarding the login issue, it is an upstream Minecraft issue, but should not happen every time. It usually logs you out only after a Minecraft Launcher update, but there is nothing I could do to fix it - it has to be fixed by Mojang.

**Comment by thermof** [comment]
oh okay

**Comment by thermof** [comment]
oh hi i do i fix lunar client problem
