### ISSUE TITLE
Uninstall Minecraft of My chromebook

### ISSUE THREAD

**Issue by MrJayBoy13** [flathub/com.mojang.Minecraft#104]
How do you do it? There is no uninstall option when you right-click.

**Comment by AsciiWolf** [comment]
How did you install it? Anyway, you should be able to uninstall it by entering this command in a terminal:
`flatpak uninstall com.mojang.Minecraft`

**Comment by MrJayBoy13** [comment]
It wont let me type my password

**Comment by MrJayBoy13** [comment]
even though i typed it right

**Comment by MrJayBoy13** [comment]
will the password be for my google account, or do i have to enter something specific?

**Comment by AsciiWolf** [comment]
Sorry, but as I already mentioned in another ticket, I don't have a Chromebook, so I am not able to help you with this. You may try adding `--user` to the previous command.

**Comment by AsciiWolf** [comment]
I am closing the ticket since it is not an issue related to this Flatpak.
