### ISSUE TITLE
No Sound on Fedora 35

### ISSUE THREAD

**Issue by Justinzobel** [flathub/com.mojang.Minecraft#107]
I have no sound coming from Minecraft. I've checked all the volumes and they are all at 100%. I can play audio from many other sources.

**Comment by AsciiWolf** [comment]
Can someone please retest this? The original issue in PipeWire was fixed and sound now works fine in Minecraft on my F35 system.

**Comment by Zlopez** [comment]
The issue is gone. The sound works normally.

**Comment by AsciiWolf** [comment]
Thanks!

**Comment by elsamuel27** [comment]
But I have the same issue in Fedora 36 now :(

**Comment by AsciiWolf** [comment]
I also have Fedora 36 (Workstation). Sound in Minecraft works fine on my system.

**Comment by clysto** [comment]
I have the same issue in Fedora 37.

**Comment by Doomsdayrs** [comment]
I have another case of this occuring with fedora 37
