### ISSUE TITLE
New launcher doesn't work

### ISSUE THREAD

**Issue by Charadon** [flathub/com.mojang.Minecraft#11]
After I log in, the launcher is just blank. Nothing in the terminal either. Anyone else getting this issue?
I'm on Debian 10 Buster

**Comment by AsciiWolf** [comment]
There has been another launcher update, see #10. It will hopefully fix the issue.

**Comment by AsciiWolf** [comment]
Launcher now works without any issue on my system. If the problem still persists, feel free to reopen this issue.
