### ISSUE TITLE
Fails to launch game

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.mojang.Minecraft#115]
[1227/190018.481074:WARNING:xproto_util.cc(51)] X error received: serial 492, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)

**Comment by AsciiWolf** [comment]
Hmm. Is this related to the already reported #113 or is it a different issue?

**Comment by alvarlagerlof** [comment]
No, this was when clicking play/launch and the other was opening anything at all.

**Comment by m93a** [comment]
I have the same problem with the newest version of launcher. Reverting to an older version using:
```
flatpak update --commit=90474627e304030f60eb1388ad7a6f331b6bf5e55dc9f9b59defbc4d8a27d5f0 com.mojang.Minecraft
flatpak mask com.mojang.Minecraft
```
did fix the issue for me.
