### ISSUE TITLE
Minecraft escaping sandbox

### ISSUE THREAD

**Issue by Goodname15** [flathub/com.mojang.Minecraft#127]
I have no idea, if this isn't just something to do with my System (Fedora Workstation Edition 36 with KDE 5.24.5), 
but when I start the launcher, pin it to the taskbar, close it and then try to launch it from there, it creates a .minecraft directory in my user folder (like non-flatpak would) and instead launches the launcher from there.
Could of course also be a KDE issue cause doing the same thing under Gnome works fine...

**Comment by AsciiWolf** [comment]
Interesting, thanks for reporting this! It indeed looks like a KDE bug.

**Comment by AsciiWolf** [comment]
If this really is a KDE bug, it is a quite serious security issue as the app is probably running directly, bypassing the Flatpak sandbox. So, please report it upstream to KDE if possible. Thanks!

**Comment by AsciiWolf** [comment]
Is this still a problem on F37 with latest KDE?

**Comment by tutacat** [comment]
Did you install it using KDiscover? Did you add any manual permissions or links?

The flatpak can read the Downloads folder, and talk to discord, but apparently not home folder.
