### ISSUE TITLE
Add Detailed Guide on How to Install Forge

### ISSUE THREAD

**Issue by mahyarmirrashed** [flathub/com.mojang.Minecraft#128]
I was going through the previous issues on this repository and scouring the internet until I found how to properly install forge.

Basically, you have to run `java -jar your_forge_jar.jar` and then navigate to `~/.var/app/com.mojang.Minecraft/.minecraft/` in the file search path that appears.

It would be nice to have this in the README for this repository.

**Comment by AsciiWolf** [comment]
The path is already mentioned in the [README](https://github.com/flathub/com.mojang.Minecraft/blob/master/README.md). Forge can be installed without the terminal command, just open the jar from a file manager (only thing needed is a JRE installed on the host system).

**Comment by mahyarmirrashed** [comment]
@AsciiWolf As this was my first time doing a forge installation, I can tell you it felt a lot harder than that. It would be in best interest to have clear instructions for those who are less experienced.

**Comment by AsciiWolf** [comment]
Feel free to send a PR. :-)

**Comment by AsciiWolf** [comment]
I believe that this is resolved now. :-)
