### ISSUE TITLE
No sound on Fedora 37

### ISSUE THREAD

**Issue by rmnvgr** [flathub/com.mojang.Minecraft#136]
Since updating to Fedora 37, there's no audio in the game. I tried changing the audio settings and starting from a fresh `~/.vap/app/com.mojang.Minecraft` directory.

When manually downloading the launcher from Mojang and running it on the host, audio works fine.

Is there anything I can do to help debugging that?

**Comment by AsciiWolf** [comment]
Thanks for your report! This may be some PipeWire/WirePlumber issue. I will try reproducing it once I upgrade to F37.

**Comment by rmnvgr** [comment]
This appears to have been fixed with the latest Pipewire update (0.3.60-4).

**Comment by clysto** [comment]
Yes, I updated pipewire and it now has sound.
