### ISSUE TITLE
No update description

### ISSUE THREAD

**Issue by veractor** [flathub/com.mojang.Minecraft#137]
How do I see the changelog for the launcher from 1121 to 1.0.1221? GNOME Software shows that the update description is unavailable.

**Comment by AsciiWolf** [comment]
There is currently no changelog available in our AppStream metadata, sadly.

**Comment by veractor** [comment]
Ah ok. Does Mojang have the changes listed somewhere so I can see what changed? Google seem to fail me.

**Comment by SystemlessDev** [comment]
You can see the changelogs inside the launcher
![image](https://user-images.githubusercontent.com/45434286/210266199-e3d6c217-b075-4ef5-8f43-23fd63e1413c.png)

**Comment by veractor** [comment]
Oh I can't believe I've missed that! Thanks for the screenshot.

**Comment by veractor** [comment]
@SystemlessDev The versions in the launcher starts with 2, which is not 1.0.1221. Where does this version number come from?

**Comment by AsciiWolf** [comment]
It comes from [here](https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json). See for example [this wiki page](https://minecraft.fandom.com/wiki/Launcher_version_history) for more details.

**Comment by veractor** [comment]
Ok, so 1.0.1221 is actually the version of `launcher-bootstrap` and the 2.3.549 comes from the `launcher-core-ado`, which has a published changelog. How do they relate to each other? I assume the former changes less often than the latter right?

**Comment by AsciiWolf** [comment]
That's correct.
