### ISSUE TITLE
Why has this not been updated in over a year on Flathub?

### ISSUE THREAD

**Issue by MagmaBro123** [flathub/com.mojang.Minecraft#144]
Title. I plan on moving to Fedora Linux sometime next year, and an actual updated package that isn't dead would be nice to see.

![image](https://github.com/flathub/com.mojang.Minecraft/assets/51277766/544850f7-0aca-4721-8e6f-b1745868392a)

Sorry if this shouldn't've been opened.

**Comment by SystemlessDev** [comment]
Because the Minecraft launcher's "core" hasn't been updated in a year. 
It has other components that is updated separately (by the MC launcher itself). This package is very much up to date :)

**Comment by MagmaBro123** [comment]
Ah, my bad then. Thought I'd ask, sorry.
