### ISSUE TITLE
Switching network during snapshot installation hung launcher.

### ISSUE THREAD

**Issue by rokejulianlockhart** [flathub/com.mojang.Minecraft#145]
I switched from my broadband connection to a hotspot.

![image](https://github.com/flathub/com.mojang.Minecraft/assets/42837531/caa3843f-c301-4461-a281-f06f635fad02)

**Comment by AsciiWolf** [comment]
Thanks for your report. This is most likely a Minecraft Launcher issue, not a Flatpak related one.

**Comment by rokejulianlockhart** [comment]
https://bugs.mojang.com/browse/MC-265195

**Comment by AsciiWolf** [comment]
Thanks!
