### ISSUE TITLE
Unset SSL_CERT_FILE at start

### ISSUE THREAD

**Issue by jakiki6** [flathub/com.mojang.Minecraft#147]
Hello,
I've been trying to get the Minecraft launcher to run using this on GNU Guix. It just simply doesn't start. As it turns out, curl terminates with `curl: (77) error setting certificate file: /run/current-system/profile/etc/ssl/certs/ca-certificates.crt` since `SSL_CERT_FILE` is set to outside of the sandbox.

It would be nice if you added it so this environment variable is unset before launching the launcher.

**Comment by AsciiWolf** [comment]
Interesting! Thank you for reporting this.

@SystemlessDev Could you take a look at this problem? Thanks!
