### ISSUE TITLE
Trying to find included java bin in Flatpak filesystem

### ISSUE THREAD

**Issue by scoronado12** [flathub/com.mojang.Minecraft#16]
Hello,

I was reading the flatpak documentation and eventually got shell access into the sandbox, of which I am trying to find the java bin because I am trying to unpack the Minecraft Forge installer into the sandbox.

I can't seem to find it in `/usr/bin` nor does `which` tell me that it is available.

**Comment by TingPing** [comment]
`/app/jre/bin/java`

**Comment by scoronado12** [comment]
> `/app/jre/bin/java`

Ty
