### ISSUE TITLE
Minecraft wont launch anymore.

### ISSUE THREAD

**Issue by Tids** [flathub/com.mojang.Minecraft#17]
I did an update a few minutes ago and now I can not launch the game anymore.
I found that there was something reverted 4h ago, however that is either broken too, or still not out on the servers.

Is there something the user can do to roll back to a working version?

**Comment by AsciiWolf** [comment]
Yep, this issue should be already fixed, the fixed version was just not published yet.

**Comment by Tids** [comment]
Ye, works now. thank you so much :+1:
