### ISSUE TITLE
"Open resource pack folder" button does not work

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.mojang.Minecraft#2]
Clicking the "Open resource pack folder" button in game Options does nothing.

**Comment by joshua-stone** [comment]
I've been able to get around this issue by running the following commands:

```
mkdir -p ~/.minecraft/resourcepacks
sudo flatpak override --filesystem=~/.minecraft/resourcepacks com.mojang.Minecraft
```

Now one can drop resource packs into `~/.minecraft/resourcepacks`, although I think ideally we should be able to store them in `~/.var/app/com.mojang.Minecraft/.minecraft/resourcepacks`.

**Comment by p1u3o** [comment]
Putting them into ~/.var/app/com.mojang.Minecraft/.minecraft/resourcepacks seems to work fine for me.

**Comment by AsciiWolf** [comment]
@p1u3o Yep, it works. The only thing that does not work is the ingame button. ;-)
