### ISSUE TITLE
Anyway to get Minecraft forge Installed

### ISSUE THREAD

**Issue by superdav42** [flathub/com.mojang.Minecraft#22]
Not sure how to begin installing Minecraft forge but it'd be nice to have.

**Comment by valentindavid** [comment]
In theory:
```
flatpak run --filesystem=~/Downloads --command=/app/jre/bin/java com.mojang.Minecraft -jar ~/Downloads/forge-1.14.4-28.1.10-installer.jar
```

But it does not work. There is a java.lang.UnsupportedOperationException because a library distributed by forge (asm-6.2.jar) is not compatible with the version of OpenJDK distributed in the Flatpak app.

**Comment by valentindavid** [comment]
I think this is related to this: https://github.com/MinecraftForge/MinecraftForge/issues/6051

**Comment by valentindavid** [comment]
If you change all `openjdk11` to `openjdk8` in `com.mojang.Minecraft.json` and rebuild it with flatpak-builder and install it, then it works.

**Comment by AsciiWolf** [comment]
There is now an openjdk8 [extension point](https://github.com/flathub/com.mojang.Minecraft/pull/50). Please, try it and let us know if it works.

**Comment by ThatGeekyWeeb** [comment]
Currently installing `org.freedesktop.Sdk.Extension.openjdk8` to test the extension point. Should report back soon.

**Comment by ThatGeekyWeeb** [comment]
the extension looks for `/usr/lib/sdk/openjdk8/jvm/java-8-openjdk` which is not the proper location of jdk
> proper location would be `/usr/lib/jvm/java-8-openjdk`

**Comment by ThatGeekyWeeb** [comment]
Script uses 
```
cd /usr/lib/jvm/java-8-openjdk 
cp -ra * /app/jdk
```
horrible way of doing this, most shells would fail to do this, using `cd` in a subshell almost never works

**Comment by ThatGeekyWeeb** [comment]
Fixed said script, to proper values

> install.sh
```
#!/bin/sh
mkdir -p /app/jre
cp -ra /usr/lib/jvm/java-1.8-openjdk/* /app/jre
rm -rf /app/jre/src.zip /app/jre/include /app/jre/demo /app/jre/sample
```

> installjdk.sh
```
#!/bin/sh
mkdir -p /app/jdk
cp -ra /usr/lib/jvm/java-1.8-openjdk/* /app/jdk
```

> enable.sh
```
#!/bin/sh
export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
export PATH=$PATH:/usr/lib/jvm/java-1.8-openjdk/bin
```

**Comment by ThatGeekyWeeb** [comment]
If the scripts are written like this, writing is done. 
Still need to test actual usage of the extension

**Comment by ThatGeekyWeeb** [comment]
If the correct branch (19.08) of `org.freedesktop.Sdk.Extension.openjdk8` is installed, proper java is loaded. By launching with "flatpak run com.mojang.Minecraft --filesystem=/app/` Minecraft can access the `/app/` folder contain the jdk build

**Comment by ThatGeekyWeeb** [comment]
If one edits the `Java Executable` to `/app/jdk8/jvm/openjdk-1.8.0_222-adoptopenjdk/bin/java` Forge 1.8.9 (Requires usage of Java 8, otherwise, no boot) Manages to boot!

**Comment by ThatGeekyWeeb** [comment]
Running server connect test from Optifine 1.8.9

**Comment by ThatGeekyWeeb** [comment]
Server Connect Test Successful! Forge *can* load mods, issue can be closed!

**Comment by AsciiWolf** [comment]
I really dislike the `--filesystem=/app/` permission "hack" and did not know that this was required when merging #50, however since it is working now, I am closing this issue. Feel free to reopen it or create a new issue if you think that a better solution should be provided.

**Comment by ThatGeekyWeeb** [comment]
As *I* mentioned [here](https://github.com/flathub/com.mojang.Minecraft/pull/50)
> Simply setting Minecraft to use `/app/jdk8/jvm/openjdk-1.8.0_222-adoptopenjdk/bin/java` for ***Java Executable*** seems to work.

`--filesystem=/app/` Is not require.
