### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.mojang.Minecraft#24]

**Comment by AsciiWolf** [comment]
I think that openjdk is not yet supported with the 19.08 fd runtime.

**Comment by AsciiWolf** [comment]
@bilelmoussaoui Build for the new commit did not start yet (and build for my other Flatpak [failed](https://flathub.org/builds/#/builders/30/builds/827/steps/13/logs/stdio)). Buildbot backend seems to have some issues at the moment.

**Comment by bilelmoussaoui** [comment]
There's some wip changes that hopefully will fix this issue. Mind triggering a new build?

**Comment by AsciiWolf** [comment]
It [seems](https://flathub.org/builds/#/builders/28/builds/1292) that it is fine now. Thanks! :-)
