### ISSUE TITLE
Leads to a whole system crash/freeze on a ryzen 2400g on archlinux

### ISSUE THREAD

**Issue by Tids** [flathub/com.mojang.Minecraft#30]
When using minecraft flatpak on a ryzen 2400g with Archlinux you can log in, press Play. a few seconds later the it'ss use 100% CPU, the mouse gets stuck and the system freezes.

There is nothing about this in any logs

we have tried to
* disable mesa shader cache (MESA_GLSL_CACHE_DISABLE=1)
* different minecraft versions
* a new user
* on wayland and pure x11
* uninstall and install all flatpaks

Without any change.

the native package just works. (Steam flatpak also works, so it shouldnt be an incompatible mesa inside of flatpak).

**Comment by AsciiWolf** [comment]
Hmm, this seems to be a possible Mesa issue. I am just making a new Minecraft Flatpak build based on 19.08 fd runtime, so let's see if it helps.

**Comment by Tids** [comment]
Yes. This one fixed it. No crashes/freezes anymore. Thanks!
