### ISSUE TITLE
Error with "Wrong size for extra data" on i386

### ISSUE THREAD

**Issue by barrychapman** [flathub/com.mojang.Minecraft#33]
Getting this error when trying to install

```

        ID                                    Arch Branch Remote  Download
 1. [✓] org.freedesktop.Platform              i386 18.08  flathub 292.7 MB / 306.7 MB
 2. [✓] org.freedesktop.Platform.Locale       i386 18.08  flathub  17.3 kB / 316.0 MB
 3. [✓] org.freedesktop.Platform.VAAPI.Intel  i386 18.08  flathub   1.9 MB / 1.9 MB
 4. [✓] org.freedesktop.Platform.html5-codecs i386 18.08  flathub   3.3 MB / 3.4 MB
 5. [✗] com.mojang.Minecraft                  i386 stable flathub 137.6 MB / 125.4 MB

Error: Wrong size for extra data https://launcher.mojang.com/download/Minecraft.tar.gz
error: Failed to install com.mojang.Minecraft: Wrong size for extra data https://launcher.mojang.com/download/Minecraft.tar.gz
```

**Comment by bilelmoussaoui** [comment]
We should use x-data-checker to avoid this in the future.

**Comment by AsciiWolf** [comment]
@bilelmoussaoui I am not sure if this would help. The Minecraft Flatpak no longer downloads extra-data from `https://launcher.mojang.com/download/Minecraft.tar.gz`, but uses a [fixed url](https://github.com/flathub/com.mojang.Minecraft/pull/13) instead. However, I think I have found the true source of this issue: The _i386_ arch. There were a i386 and aarch64 Minecraft Flatpak builds available for a short period of time, however they actually never worked (Minecraft launcher binaries are x86_64-only) and were [disabled](https://github.com/flathub/com.mojang.Minecraft/commit/112db80afb02cf6eaa116c519c9b60ddd38886eb) afterwards. Problem is that such builds are not deleted from Flathub (the same issue happens with EOL Flatpaks).

**Comment by bilelmoussaoui** [comment]
I missed that they were trying to install the i386 build. In such case, this depends on https://github.com/flathub/flathub/issues/1196 being fixed first.

**Comment by AsciiWolf** [comment]
Does this still happen? If so, could please someone correctly EOL the Minecraft Flatpak on i386?

/cc @barthalion

**Comment by cho2** [comment]
I try to install it on Raspi 4 today and got the same error

```
flatpak install flathub com.mojang.Minecraft -y
Mencari kecocokan...


com.mojang.Minecraft izin:
    ipc          network     pulseaudio     x11     dri
    tags [1]

    [1] proprietary


        ID                      Cabang    Op   Remote    Unduh
 1. [✗] com.mojang.Minecraft    stable    i    flathub   63,6 MB / 129,0 MB

Galat: Ukuran yang salah untuk data ekstra https://launcher.mojang.com/download/Minecraft.tar.gz
galat: Gagal untuk pasang com.mojang.Minecraft: Ukuran yang salah untuk data ekstra https://launcher.mojang.com/download/Minecraft.tar.gz
```

Based on this [commit](https://github.com/flathub/com.mojang.Minecraft/commit/112db80afb02cf6eaa116c519c9b60ddd38886eb), looks like i386 and aarch64 are dropped

**Comment by barthalion** [comment]
I have deleted i386 and aarch64 refs completely to avoid confusion.
