### ISSUE TITLE
Update the extra-data automatically

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.mojang.Minecraft#36]
Minecraft launcher gets a lot of new updates and when there is a new update available, it shows a notification every time it is launched. Some mechanism to do the updates (Pull requests) automatically would help a lot. Maybe we could use [x-data-checker](https://github.com/flathub/flatpak-external-data-checker) for this?

**Comment by klausenbusk** [comment]
So need some logic which check `https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json` regularly and do a commit automatic?

It can be done by using [GitHub Actions](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule). I would look into it!

**Comment by barthalion** [comment]
@klausenbusk New checker for https://github.com/flathub/flatpak-external-data-checker would be preferred.

**Comment by klausenbusk** [comment]
PR opened: https://github.com/flathub/com.mojang.Minecraft/pull/42
