### ISSUE TITLE
Minecraft just disappears

### ISSUE THREAD

**Issue by oksoft-git** [flathub/com.mojang.Minecraft#37]
I installed Minecraft, started, connected into server. Everything is working fine, but if I switch to Firefox And wait it just disappears. If i run it in terminal, process just closes itself.
Note: i didnt allowed running on background when gtk portal asked me. So if this problem Is here, please tell my how to allow it.

**Comment by AsciiWolf** [comment]
Hmm, that's strange. Any chance you could get some logs?

**Comment by oksoft-git** [comment]
> Hmm, that's strange. Any chance you could get some logs?

I think not, because it just - closes the Minecraft, like closing by cross button

**Comment by AsciiWolf** [comment]
Can you try running `flatpak run com.mojang.Minecraft` in a terminal?

**Comment by AsciiWolf** [comment]
I was not able to reproduce your issue. If you use GNOME, the gtk portal will display a notification regarding the background usage that you can allow/disallow/ignore.
