### ISSUE TITLE
Wrong branch for io.atom.electron.BaseApp

### ISSUE THREAD

**Issue by valentindavid** [flathub/com.mojang.Minecraft#38]
Trying to build locally the application I discovered that it requires `io.atom.electron.BaseApp//stable` which depends on Freedesktop SDK 1.6. It should be using `io.atom.electron.BaseApp//19.08` instead to be sure to use a build of electron that is ABI compatible with Freedesktop SDK 19.08.

**Comment by AsciiWolf** [comment]
Thanks for pointing out this issue! Feel free to send a PR. :-)
