### ISSUE TITLE
Possible legal issues?

### ISSUE THREAD

**Issue by kolgza** [flathub/com.mojang.Minecraft#4]
Minecraft was removed from the Snap store [because the Snapcrafters didn't have the proper permission to redistribute it.](https://forum.snapcraft.io/t/where-did-the-minecraft-snap-go/10238/2)

Did the Flathub maintainers contact Mojang about this yet?

**Comment by AsciiWolf** [comment]
The only thing distributed with this Flatpak is the game icon. The actual game launcher is downloaded from Mojang.com and unpacked using extra-data when installing the Flatpak. So everything should be fine.
