### ISSUE TITLE
Skin editor in Launcher does not work on AMD GPUs

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.mojang.Minecraft#45]
The "Skins" tab in Minecraft Launcher does not work when using AMD GPU. It seems that it tries to load `/app/extra/minecraft-launcher/swiftshader/libGLESv2.so` that does not exist for some reason.

**Comment by AsciiWolf** [comment]
Seems to be a [known issue](https://bugs.mojang.com/browse/MCL-12546).

**Comment by AsciiWolf** [comment]
The issue has been fixed in latest launcher.

**Comment by klausenbusk** [comment]
I can confirm that it works perfectly with a Intel GPU, weird..

**Comment by AsciiWolf** [comment]
Seems to be fixed in latest launcher version 887 (#78).

**Comment by AsciiWolf** [comment]
I can confirm that this now works fine on AMD GPU.
