### ISSUE TITLE
Include java8 to add compatibility with older versions of Minecraft

### ISSUE THREAD

**Issue by ghost** [flathub/com.mojang.Minecraft#5]
Without java8 older versions of Minecraft don't run correctly. For example Minecraft 1.8.9 will not connect to servers with the error message: Unable to access address of buffer which is resolved if java 8 is used.

**Comment by nedrichards** [comment]
Java 8 had some significant issues whilst this flatpak was being worked on with e.g. SSL etc. which meant that it didn't really work at all for minecraft.

**Comment by jean730** [comment]
Minecraft 1.12.2 + forge does not launch unless i add 

`[Extension org.freedesktop.Sdk.Extension.openjdk8]
version=18.08
directory=/jre`
in the metadata and replace
`[Environment]
JAVA_HOME=/app/jre/`
with
`[Environment]
JAVA_HOME=/app/jre/jvm/openjdk-1.8.0-internal/jre/`

**Comment by jean730** [comment]
Minecraft 1.12.2 + forge does not launch unless i add

`[Extension org.freedesktop.Sdk.Extension.openjdk8]
version=18.08
directory=/jre`
in the metadata and replace
`[Environment]
JAVA_HOME=/app/jre/`
with
`[Environment]
JAVA_HOME=/app/jre/jvm/openjdk-1.8.0-internal/jre/`

**Comment by valentindavid** [comment]
@nedrichards It would be nice to know a bit more about those issues. Because I have not seen any issue running Minecraft openjdk 8.

**Comment by BuggStream** [comment]
> Minecraft 1.12.2 with forge does not launch unless i add
> 
> `[Extension org.freedesktop.Sdk.Extension.openjdk8] version=18.08 directory=/jre`
> in the metadata and replace
> `[Environment] JAVA_HOME=/app/jre/`
> with
> `[Environment] JAVA_HOME=/app/jre/jvm/openjdk-1.8.0-internal/jre/`

I had the exact same issue today. Flatpak noob here, but I assume this can only be added if you rebuild it? So it is not possible to just override a setting or something similar?

**Comment by ThatGeekyWeeb** [comment]
As I mentioned both on #22 and #50.

> If the correct branch (19.08) of `org.freedesktop.Sdk.Extension.openjdk8` is installed, proper java is _installed_. If one edits the _**Java Executable**_ to `/app/jdk8/jvm/openjdk-1.8.0_222-adoptopenjdk/bin/java` Java8 is used.
