### ISSUE TITLE
Possible to add minecraft flatpak to steam flatpak library?

### ISSUE THREAD

**Issue by ptalbert** [flathub/com.mojang.Minecraft#51]
Steam has an option to "Add a non-steam game to my library". So, using both steam and minecraft installs from flathub, is there a way to add minecraft to Steam's library? This allows the game to be played via steam link.

The immediate issue is that the sandbox steam is running in cannot see minecraft.

**Comment by AsciiWolf** [comment]
Sorry, I don't think it is actually possible, see [this](https://github.com/flathub/com.valvesoftware.Steam/issues/278) ticket. Anyway, I think that [this](https://github.com/flathub/com.valvesoftware.Steam/issues) is a better place to ask this question.
