### ISSUE TITLE
OpenJDK 11 cause Forge to crash

### ISSUE THREAD

**Issue by JasonHK** [flathub/com.mojang.Minecraft#57]
According to the [post](https://forums.minecraftforge.net/topic/70670-forge-1132-crashes-right-away/?tab=comments#comment-341941) in Forge Forums, Forge only supports Java 8-10. But this package ships with OpenJDK 11.

This might be the reason why the game crashed at launch when and only when Forge is used.

**Comment by AsciiWolf** [comment]
Did you try using the _org.freedesktop.Sdk.Extension.openjdk8_ extension?

**Comment by Aditoo17** [comment]
Could you please explain how to install the extension? I tried `flatpak install org.freedesktop.Sdk.Extension.openjdk8` and added `/app/jdk8/jvm/openjdk-1.8.0_222-adoptopenjdk/bin/java` to the profile in the launcher, but it didn't work. I don't think I understand what to do.

**Comment by AsciiWolf** [comment]
Hmm, that's weird. @tilosp @ThatGeekyWeeb Do you have any idea what could be wrong?

**Comment by ThatGeekyWeeb** [comment]
Alright sure, it's highly possible the wrong version of it was installed, this was the original issue I had.


> https://github.com/flathub/com.mojang.Minecraft/issues/22
> If the correct branch (`19.08`) of `org.freedesktop.Sdk.Extension.openjdk8` is installed, proper java is installed. 
I recommend re-installing and checking if you used the correct branch!

NOTE: atm I am not using flathub, and storage is limited for me, so I have no space to test it and projects within it, I am also working on a extremely big project atm (1k+ lines of code(9k+ after compile) so I may be slow to respond

**Comment by AsciiWolf** [comment]
I think that this should be fixed now - latest Minecraft Launcher uses bundled Java. Please retest and let us know. Thanks!

**Comment by SystemlessDev** [comment]
> I think that this should be fixed now - latest Minecraft Launcher uses bundled Java. Please retest and let us know. Thanks!

Already tested it and it indeed works! This issue can be closed now

**Comment by AsciiWolf** [comment]
Thanks!
