### ISSUE TITLE
Update runtime to 20.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.mojang.Minecraft#63]

**Comment by AsciiWolf** [comment]
I am not sure if OpenJDK is available with fd 20.08 runtime. Anyway, feel free to send a PR.

**Comment by eszlari** [comment]
This needs to be done first: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8/issues/9

**Comment by cxrvh** [comment]
OpenJDK8 is now available for 20.08.

**Comment by AsciiWolf** [comment]
Feel free to send a PR. :-)

**Comment by joshua-stone** [comment]
It appears that [io.atom.electron.BaseApp](https://github.com/flathub/io.atom.electron.BaseApp/pull/8) also needs to be updated to 20.08.

**Comment by AsciiWolf** [comment]
Both OpenJDK and Electron BaseApp now should have proper 20.08 branches (although the build for Electron BaseApp is currently waiting to be published). I will try to update the Minecraft Flatpak runtime tomorrow. :-)
