### ISSUE TITLE
Launcher Update Available

### ISSUE THREAD

**Issue by Justinzobel** [flathub/com.mojang.Minecraft#76]
Title says it all, thanks for the great work!

**Comment by AsciiWolf** [comment]
Thanks! Client updates are handled automatically by x-data-checker - PR is created by a bot when an update is available. I wonder why it was not created yet, but it will surely be updated in upcoming days.

**Comment by AsciiWolf** [comment]
Hmm, I wonder why the PR was not created yet. Maybe the x-data-checker bot has some issues.

**Comment by wjt** [comment]
I don't know about Bilal but I don't have access to the bot's logs AFAIK. @barthalion @gasinvein are you able to look at what's happening?

**Comment by gasinvein** [comment]
@wjt Logs are available to everyone at the [flathub repo actions](https://github.com/flathub/flathub/actions/workflows/external-data-checker.yml).

@AsciiWolf Your `x-checker-data` results in constructing URLs with http 404. Maybe updstream files are served from a different URL now?
In the meantime, you can use/test flatpak-external-data-checker locally, it's available as [a flatpak](https://github.com/flathub/org.flathub.flatpak-external-data-checker) and as [docker image](https://github.com/orgs/flathub/packages/container/package/flatpak-external-data-checker).

**Comment by AsciiWolf** [comment]
So, it looks like that the naming scheme for Minecraft Launcher has changed, but the [json file](https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json) we parse did not follow this change and is still using the old one. [This page](https://minecraft.gamepedia.com/Launcher_version_history) also still uses the old naming scheme and shows `2.2.2159` as the latest Linux version. But the actual latest package version is `887`, according to the official Arch Linux AUR package. I will update the Flatpak manually and keep this issue open until a proper solution is found.

**Comment by AsciiWolf** [comment]
Hmm, actually, it looks like the json file has the `887` version entry. So, the only thing we probably need to fix is the x-data-checker version-pattern.

**Comment by gasinvein** [comment]
Once you figure out Mincraft versions, consider also switching to the json checker (based on [jq](https://stedolan.github.io/jq/)). It allows you to to process json structure and is much more precise than a regex.

**Comment by AsciiWolf** [comment]
Thanks. I have prepared the manual update, see #78, unfortunately it does not seem to work. I will fix the x-data-checker after this is resolved.
