### ISSUE TITLE
Minecraft 1.17 requires java 16

### ISSUE THREAD

**Issue by SystemlessDev** [flathub/com.mojang.Minecraft#80]
The newest release, and future releases of Minecraft, are compiled with java 16 as the minimum requirement. 

This package should migrate from using java 11 to java 16 by default because of this.

It shouldn't affect earlier versions any differently than java 11 already is.

**Comment by AsciiWolf** [comment]
This will be fixed when #83 is merged, right? (Latest Minecraft Launcher now uses bundled Java.)

**Comment by vchernin** [comment]
I am already able to run 1.17 with the current launcher in #85, so I think the only thing we need to do is remove the unnecessary Java modules, which is done in both #83 and #85.
