### ISSUE TITLE
Instalation fails, wrong Minecraft.tar.gz size

### ISSUE THREAD

**Issue by AlexKF98** [flathub/com.mojang.Minecraft#9]
From what I see, the correct size and sha256sum for Minecraft.tar.gz are respectively 66669820 and 887214f4291e3e7b2e042840c2682af6c1a21a3296294b29ac1c63d4a00b467d. It's not 66992368 and 61024d7573e82d8b4c730f01b7a74e4c925bfb62e2473570fe4b16a04df56816.

**Comment by Docmine7** [comment]
Here same problem for update or install

**Comment by AsciiWolf** [comment]
Will be fixed after #10 is updated and merged.
