### ISSUE TITLE
Launcher doesn't scale correctly on HiDPI

### ISSUE THREAD

**Issue by vchernin** [flathub/com.mojang.Minecraft#93]
The latest launcher doesn't seem to be able to scale properly on a HiDPI display.

My display is scaled to 200% but the launcher content is at 100%. The actual game is fine, this is only about the launcher.

The older launchers were all blurry at HiDPI, so this is still an improvement.

Tried running the CEF launcher in native Wayland with `flatpak run com.mojang.Minecraft --enable-features=UseOzonePlatform --ozone-platform=wayland` but Chromium is version 86, native Wayland is only experimentally supported in 87+.

Running Gnome 40 Wayland on Fedora Silverblue.

**Comment by SystemlessDev** [comment]
Seems to be a known issue with the launcher https://bugs.mojang.com/browse/MCL-10940

It has also been open since mid 2019 so I wouldn't assume it's going to be fixed anytime soon.

**Comment by vchernin** [comment]
Hopefully when they update the launcher to Chromium 87 it can be workarounded with Wayland support.

Maybe I'll see if I can mess around with all the scaling variables at some point.

**Comment by vchernin** [comment]
This is an upstream bug
