### ISSUE TITLE
Launcher displays error when being started for a first time

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.mojang.Minecraft#94]
When running the Minecraft Flatpak for a first time and logging in, error message is displayed instead of the "Play" tab in the game launcher:

![error](https://user-images.githubusercontent.com/2339930/126490545-95a8f96b-60a3-4cfa-a4bb-aece33713e0d.png)

I am not sure whether this is a Flatpak-related issue or not, however it is very easy to workaround: Just close the launcher and run it again.

**Comment by SystemlessDev** [comment]
It's a known launcher bug affecting all platforms https://bugs.mojang.com/browse/MCL-18214

**Comment by SystemlessDev** [comment]
fixed upstream as of August 2nd 2021

![image](https://user-images.githubusercontent.com/45434286/127927814-d45b595c-351a-4b3d-99bd-70a4a06bc774.png)

**Comment by SystemlessDev** [comment]
Why is this issue still open?

**Comment by AsciiWolf** [comment]
Because I forgot to close it. :-)
