### ISSUE TITLE
Launcher does not use system mouse pointer theme

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.mojang.Minecraft#95]
Default X11 cursor theme seems to be used in the game launcher instead of a correct (Adwaita in my case) system one.

**Comment by SystemlessDev** [comment]
Seems like we can bypass this issue by allowing it read only access to 
`/home/$USER/.icons/` and `/usr/share/icons/`

source: https://github.com/flatpak/flatpak/issues/709

**Comment by AsciiWolf** [comment]
That sounds like a workaround, not a proper fix, to me. But thanks for pointing this out. :-)

**Comment by SystemlessDev** [comment]
> That sounds like a workaround, not a proper fix, to me. But thanks for pointing this out. :-)

Well yeah of course? There is no other fix except installing the icon theme as a flatpak package

**Comment by AsciiWolf** [comment]
Hmm, that's strange. I do not have issues with mouse pointer in other Flatpaks.
