### ISSUE TITLE
[Chromebook] Dragging a block to inventory glitches the game

### ISSUE THREAD

**Issue by Myst3o** [flathub/com.mojang.Minecraft#97]
When i go in creative and i drag a block to my inventory my game has black switching on and on repeatedly and the only way i can get out of it is to close minecraft. The only way i can get blocks is by doing pick block or using commands

**Comment by AsciiWolf** [comment]
Thanks for your report. What GPU (and GPU drivers) do you have? It works fine on my machine running AMD RX 550 with Mesa 21.1.4.

**Comment by Myst3o** [comment]
how do i check my gpu?

**Comment by AsciiWolf** [comment]
It depends on your system (Linux distribution / desktop environment). But if you are able to use Terminal, you can check it using this command: `lspci|grep VGA`

**Comment by Myst3o** [comment]
![image](https://user-images.githubusercontent.com/88152632/127568320-8f1416d4-c231-47d3-ae71-5faad7b00f1f.png)

**Comment by AsciiWolf** [comment]
Oops, sorry, you probably have to run this command with sudo: `sudo lspci|grep VGA`

**Comment by Myst3o** [comment]
![image](https://user-images.githubusercontent.com/88152632/127584889-a2170242-94bf-40bd-aa7c-6d08a58a482b.png)

**Comment by AsciiWolf** [comment]
Interesting. Maybe try using `sudo /sbin/lspci|grep VGA` or `sudo /usr/sbin/lspci|grep VGA`. What Linux distribution do you have on your PC?

**Comment by Myst3o** [comment]
![image](https://user-images.githubusercontent.com/88152632/127695857-3fae4b71-7d87-45be-87b9-8359823b8722.png)

**Comment by Myst3o** [comment]
What do you mean what distribution do i have on my pc? Also it's a chromebook

**Comment by AsciiWolf** [comment]
Ah! Well, I have no way of testing this on a Chromebook, because I don't have one, but it works fine on both my computers running AMD and Intel GPUs.

**Comment by Myst3o** [comment]
aw...

**Comment by NateMedina42309** [comment]
Hey, you told me to leave the comment here, and basically the same thing as him is happening with me, can you please help me out with this?

**Comment by AsciiWolf** [comment]
Sorry, I am not able to help you since I don't have any experience with Chromebooks. You can try upgrading Mesa inside the Linux container, but I don't know any details how to do it.

**Comment by AsciiWolf** [comment]
As a workaround, you can try installing a non-Flatpak version of Minecraft. Here is some video guide how to do it: https://www.youtube.com/watch?v=tx3CHDkrMTE

**Comment by AsciiWolf** [comment]
As a workaround, you can try installing a non-Flatpak version of Minecraft. Here is some video guide how to do it: https://www.youtube.com/watch?v=tx3CHDkrMTE

But I don't have any experience with this and it may not work as well.

**Comment by SystemlessDev** [comment]
I mean if the game itself is freaking out this probably isn't our issue. 

> Hey, you told me to leave the comment here, and basically the same thing as him is happening with me, can you please help me out with this?

Can you send the crash report from when you're crashing?

> When i go in creative and i drag a block to my inventory my game has black switching on and on repeatedly and the only way i can get out of it is to close minecraft. The only way i can get blocks is by doing pick block or using commands

Are you testing this with 1.17.1?

**Comment by NateMedina42309** [comment]
Yes, I am using 1.17 AND 1.17.1. I just really want to use the new stuff in
1.17.

**Comment by SystemlessDev** [comment]
> Yes, I am using 1.17 AND 1.17.1. I just really want to use the new stuff in 1.17.

I'd assume this is a vanilla issue in that case. What chromebook do you have

**Comment by NateMedina42309** [comment]
My chromebook is a Samsung Chromebook 4, and 1.16.5 works just fine.

**Comment by SystemlessDev** [comment]
> My chromebook is a Samsung Chromebook 4, and 1.16.5 works just fine.

Then that proves my suspicion even further. Between 1.16.5 and 1.17 there was a major change: migrating from java 8 to java 16. So that's probably the issue here.  You could try installing some separate version of openjdk 16 and get the game to use that to try to troubleshoot it. But at this point it's far from anything we can fix up on our side.

**Comment by NateMedina42309** [comment]
Thanks for the tip! ill try after school

**Comment by SystemlessDev** [comment]
I am closing this considering how this is a vanilla issue and can't be reasonably fixed by us.
