### ISSUE TITLE
Can't start Minecraft Launcher

### ISSUE THREAD

**Issue by marcelovbcfilho** [flathub/com.mojang.Minecraft#99]
## What Happened

I was trying to open the minecraft launcher to play, after download a linux.json file the launcher crashes.
Image showing what is downloading before the launcher crashes.
![Screenshot from 2021-08-11 09-11-26](https://user-images.githubusercontent.com/51462138/129026453-2773b096-bce9-4859-a5c3-e234fced82bd.png)

## Expected Behavior

The launcher open.

### Logs

When I run the launcher through the command line i get these messages:
```
https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json

(process:2): Gtk-WARNING **: 09:06:49.175: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 09:06:49.248: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:06:49.248: Failed to load module "canberra-gtk-module"
OK
https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid

```

## Platform Information

Elementary OS 6 stable release.

**Comment by AsciiWolf** [comment]
Thanks for your report. This seems to be the same issue as #25, please report it there instead. Thanks.
